In [1]:
import pandas as pd

sales = pd.read_csv('../data/clean/sales.csv')
prices = pd.read_parquet('../data/processed/prices_stores_CA.parquet')

In [2]:
calendar = pd.read_parquet('../data/processed/calendar_subset.parquet')

In [3]:
calendar.columns

Index(['date', 'wm_yr_wk', 'd'], dtype='str')

In [4]:
prices = prices.merge(calendar, on= "wm_yr_wk", how= 'left')

In [5]:
print(prices.columns,
prices.shape
)
prices

Index(['store_id', 'item_id', 'wm_yr_wk', 'sell_price', 'date', 'd'], dtype='str') (9320159, 6)

        store_id        item_id  wm_yr_wk  sell_price        date       d
0           CA_1  HOBBIES_1_001     11325        9.58  2013-07-13   d_897
1           CA_1  HOBBIES_1_001     11325        9.58  2013-07-14   d_898
2           CA_1  HOBBIES_1_001     11325        9.58  2013-07-15   d_899
3           CA_1  HOBBIES_1_001     11325        9.58  2013-07-16   d_900
4           CA_1  HOBBIES_1_001     11325        9.58  2013-07-17   d_901
...          ...            ...       ...         ...         ...     ...
9320154     CA_2    FOODS_3_827     11620        1.00  2016-06-15  d_1965
9320155     CA_2    FOODS_3_827     11620        1.00  2016-06-16  d_1966
9320156     CA_2    FOODS_3_827     11620        1.00  2016-06-17  d_1967
9320157     CA_2    FOODS_3_827     11621        1.00  2016-06-18  d_1968
9320158     CA_2    FOODS_3_827     11621        1.00  2016-06-19  d_1969

[9320159 rows x 6 columns]

In [6]:
print(prices["item_id"].nunique())

3049

In [7]:
prices_filtered = prices[prices["item_id"].isin(sales["item_id"])]
prices_filtered.shape

(185861, 6)

In [8]:
prices_filtered

        store_id      item_id  wm_yr_wk  sell_price        date       d
2601684     CA_1  FOODS_1_018     11101         1.0  2011-01-29     d_1
2601685     CA_1  FOODS_1_018     11101         1.0  2011-01-30     d_2
2601686     CA_1  FOODS_1_018     11101         1.0  2011-01-31     d_3
2601687     CA_1  FOODS_1_018     11101         1.0  2011-02-01     d_4
2601688     CA_1  FOODS_1_018     11101         1.0  2011-02-02     d_5
...          ...          ...       ...         ...         ...     ...
9291185     CA_2  FOODS_3_808     11620         1.0  2016-06-15  d_1965
9291186     CA_2  FOODS_3_808     11620         1.0  2016-06-16  d_1966
9291187     CA_2  FOODS_3_808     11620         1.0  2016-06-17  d_1967
9291188     CA_2  FOODS_3_808     11621         1.0  2016-06-18  d_1968
9291189     CA_2  FOODS_3_808     11621         1.0  2016-06-19  d_1969

[185861 rows x 6 columns]

In [16]:
weekly_price = prices_filtered.groupby(["item_id","wm_yr_wk"])["sell_price"].mean().reset_index()

In [17]:
weekly_price.to_csv('../data/clean/weekly_price.csv', index=False)